PeopleTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PeopleTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S 
      - AttributeName: genero
        AttributeType: S   
      - AttributeName: creado
        AttributeType: S  
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: genderAndCreated
        KeySchema:
          - AttributeName: genero
            KeyType: HASH    
          - AttributeName: creado
            KeyType: RANGE
        Projection:
          ProjectionType: ALL