PlanetsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PlanetsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S 
      - AttributeName: poblacion
        AttributeType: S   
      - AttributeName: creado
        AttributeType: S  
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: populationAndCreated
        KeySchema:
          - AttributeName: poblacion
            KeyType: HASH    
          - AttributeName: creado
            KeyType: RANGE
        Projection:
          ProjectionType: ALL